trigger:
- main

pool:
  name: Default   # use Default (your working pool)

steps:

# Step 1: Build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

# Step 2: Simulate Deployment
- script: |
    echo "Simulating deployment..."
    mkdir deployed
    copy target\*.jar deployed\
    echo "Deployment successful!"
  displayName: 'Simulate Deployment'

# Step 3: Run Application
- script: |
    echo "Running the JAR file..."
    dir deployed
    for %%f in (deployed\*.jar) do java -jar "%%f"
  displayName: 'Run Application'